"""Smoke tests for parametric (linear, unsmoothed) terms — `bs="parametric"`.

Status: SCAFFOLD. The end-to-end path runs and the parametric column shows
up correctly in the design matrix, but byte-for-byte mgcv parity is **not**
closed yet. See `docs/PARAMETRIC_TERMS_DESIGN.md` for the open items.

The reference parity data was generated by
`scripts/r/tests/generate_parametric_parity.R` and lives at
`test_data/parametric_parity_n300.json`. mgcv-side values for n=300:

    intercept  ≈ 0.00731
    dummy coef ≈ 0.6887   (true DGP coef = 0.7)
    lambda s(x)≈ 0.00163
    sigma^2    ≈ 0.00984
    EDF s(x)   ≈ 8.66
    EDF dummy  = 1.0

These smoke tests verify:

1. The fit completes without error when one column is marked parametric.
2. The design matrix has the right shape (no spline expansion on the
   parametric column).
3. The fitted parametric coefficient is in the right ballpark — recovers
   the linear shift to within a few percent on this clean DGP. (Not the
   tight 1e-6 bar we use for closed parity tests; this is a scaffold-level
   sanity check.)
"""

from __future__ import annotations

import json
import os

import numpy as np
import pytest

from mgcv_rust import Gam


PARITY_PATH = os.path.join(
    os.path.dirname(__file__),
    "..",
    "..",
    "test_data",
    "parametric_parity_n300.json",
)


@pytest.fixture(scope="module")
def parity_ref() -> dict:
    """Load the mgcv parity reference dataset (training data + outputs)."""
    if not os.path.exists(PARITY_PATH):
        pytest.skip(
            f"parametric parity reference not found at {PARITY_PATH}. "
            "Regenerate with `Rscript scripts/r/tests/generate_parametric_parity.R`."
        )
    with open(PARITY_PATH) as f:
        return json.load(f)


def test_parametric_smoke_end_to_end(parity_ref):
    """Fit `y ~ s(x) + dummy` with `dummy` flagged parametric — should run."""
    data = parity_ref["data"]
    x = np.asarray(data["x"], dtype=float)
    dummy = np.asarray(data["dummy"], dtype=float)
    y = np.asarray(data["y"], dtype=float)

    X = np.column_stack([x, dummy])

    gam = Gam(
        predictors=["x", "dummy"],
        predictor_basis_map={"dummy": "parametric"},
        k_default=10,
        family="gaussian",
    )
    gam.fit(X, y)

    # Basic invariants that should hold even before full parity closure.
    coef = gam.get_coefficients()
    assert coef.ndim == 1
    # 1 intercept + 9 (k=10 sum-to-zero) for s(x) + 1 for parametric dummy = 11
    assert coef.size == 11, f"unexpected coef length: {coef.size}"

    # Predictions should run end-to-end.
    yhat = gam.predict(X)
    assert yhat.shape == y.shape
    assert np.all(np.isfinite(yhat)), "non-finite predictions from parametric fit"


def test_parametric_design_matrix_layout(parity_ref):
    """The parametric column should contribute exactly ONE design column.

    Structural check: with x (k=10 → 9 columns after sum-to-zero) and dummy
    (parametric → 1 column), the total design column count is
    `1 (intercept) + 9 + 1 = 11`. We do NOT yet match mgcv's column ORDER
    (mgcv puts parametric before smooth — see TODO #1 in the design doc),
    only the count.
    """
    data = parity_ref["data"]
    x = np.asarray(data["x"], dtype=float)
    dummy = np.asarray(data["dummy"], dtype=float)
    y = np.asarray(data["y"], dtype=float)

    X = np.column_stack([x, dummy])

    gam = Gam(
        predictors=["x", "dummy"],
        predictor_basis_map={"dummy": "parametric"},
        k_default=10,
        family="gaussian",
    )
    gam.fit(X, y)

    design = gam.get_design_matrix()
    n_mgcv, p_mgcv = parity_ref["mgcv"]["lpmatrix_dims"]
    assert design.shape == (n_mgcv, p_mgcv), (
        f"design shape {design.shape} != mgcv shape ({n_mgcv}, {p_mgcv})"
    )


def test_parametric_coefficient_in_ballpark(parity_ref):
    """The fitted dummy coefficient should be close to the true DGP shift.

    True coefficient is 0.7; mgcv recovers 0.6887. On the n=300 scaffold the
    Rust path lands at ~0.6890 (diff ~3e-4 vs mgcv), so we use a 5e-3
    tolerance — tight enough to catch a real regression but slack enough to
    absorb the residual penalty-scaling gap (see PARAMETRIC_TERMS_DESIGN.md
    TODO list, and the `mgcv_exact` machinery for the unrelated lambda-scale
    delta we see on s(x)). Full 1e-6 byte-for-byte parity is a followup.
    """
    data = parity_ref["data"]
    x = np.asarray(data["x"], dtype=float)
    dummy = np.asarray(data["dummy"], dtype=float)
    y = np.asarray(data["y"], dtype=float)

    X = np.column_stack([x, dummy])

    gam = Gam(
        predictors=["x", "dummy"],
        predictor_basis_map={"dummy": "parametric"},
        k_default=10,
        family="gaussian",
    )
    gam.fit(X, y)

    coef = gam.get_coefficients()
    term_indices = dict(
        (name, (first, last)) for name, first, last in gam._native.get_term_indices()
    )

    # Our column layout (current): [intercept | s(x) cols (9) | dummy col (1)].
    # The parametric "smooth" is the second registered smooth term (x1).
    # get_term_indices() returns (name, first_col, last_col).
    assert "x1" in term_indices, f"expected x1 in term_indices, got {term_indices}"
    first, last = term_indices["x1"]
    # parametric ⇒ exactly one column
    assert last - first == 0, (
        f"parametric term should occupy 1 column; got first={first}, last={last}"
    )

    dummy_coef = float(coef[first])
    mgcv_dummy = float(parity_ref["mgcv"]["coef"]["dummy"])

    # Scaffold-level: 5e-3 absolute. Observed diff on n=300 is ~3e-4.
    assert abs(dummy_coef - mgcv_dummy) < 5e-3, (
        f"dummy coef {dummy_coef:.6f} is far from mgcv's {mgcv_dummy:.6f} "
        f"(|diff|={abs(dummy_coef - mgcv_dummy):.6f}). Scaffold bar is 5e-3."
    )

    # Sanity: the coefficient should NOT be tiny — that would mean the
    # parametric term is being penalised away.
    assert abs(dummy_coef) > 0.3, (
        f"dummy coef {dummy_coef:.4f} is suspiciously small — parametric "
        "term may be getting unintentionally penalised."
    )


def test_parametric_fitted_values_close_to_mgcv(parity_ref):
    """Fitted values should track mgcv's at scaffold-level precision.

    Observed on n=300: MAE ~1.2e-3, max diff ~4.4e-3. Bar is 5e-3 mean and
    1e-2 max — closing the residual penalty-scaling gap should tighten
    these. See PARAMETRIC_TERMS_DESIGN.md.
    """
    data = parity_ref["data"]
    x = np.asarray(data["x"], dtype=float)
    dummy = np.asarray(data["dummy"], dtype=float)
    y = np.asarray(data["y"], dtype=float)

    X = np.column_stack([x, dummy])

    gam = Gam(
        predictors=["x", "dummy"],
        predictor_basis_map={"dummy": "parametric"},
        k_default=10,
        family="gaussian",
    )
    gam.fit(X, y)
    yhat = gam.predict(X)
    mgcv_fit = np.asarray(parity_ref["mgcv"]["fitted"], dtype=float)
    mae = float(np.mean(np.abs(yhat - mgcv_fit)))
    max_diff = float(np.max(np.abs(yhat - mgcv_fit)))
    assert mae < 5e-3, f"MAE vs mgcv = {mae:.6g} (bar 5e-3)"
    assert max_diff < 1e-2, f"max diff vs mgcv = {max_diff:.6g} (bar 1e-2)"


def test_parametric_lpmatrix_predict_path(parity_ref):
    """`evaluate_lpmatrix` on new data should preserve the parametric column.

    The parametric column at predict-time is just the raw covariate values,
    same as fit-time. This catches a regression where `evaluate_for_predict`
    might wrongly route through a basis transform.
    """
    data = parity_ref["data"]
    x = np.asarray(data["x"], dtype=float)
    dummy = np.asarray(data["dummy"], dtype=float)
    y = np.asarray(data["y"], dtype=float)

    X = np.column_stack([x, dummy])

    gam = Gam(
        predictors=["x", "dummy"],
        predictor_basis_map={"dummy": "parametric"},
        k_default=10,
        family="gaussian",
    )
    gam.fit(X, y)

    # Pick a few rows for the predict-time test
    X_new = X[:5]
    lp = gam.evaluate_lpmatrix(X_new)

    term_indices = dict(
        (name, (first, last)) for name, first, last in gam._native.get_term_indices()
    )
    first, last = term_indices["x1"]
    assert last - first == 0

    # The parametric column at predict time must equal the raw dummy values
    # in those rows.
    np.testing.assert_allclose(
        lp[:, first],
        X_new[:, 1],
        rtol=0,
        atol=0,
        err_msg="parametric column at predict-time should equal raw covariate",
    )
